### ISSUE TITLE
Support for automated backups (DB)

### ISSUE THREAD

**Issue by prometheanfire** [immich-app/immich-charts#108]
The official docs reference using a container for DB backups.  It'd be nice if that were supported as an optional additional container to deploy for this app.

https://immich.app/docs/administration/backup-and-restore/

Filesystem wise I imagine would depend on the backing store/driver in use for the cluster.

**Comment by bo0tzz** [comment]
For the compose setup, using a container like that is a reasonable approach to backups. In my opinion, on a kubernetes cluster, the much better option is to use a real postgres operator that handles everything including backups for you.

**Comment by prometheanfire** [comment]
This chart seems to assume that it deploys it's own DB.  If using an operator is expected then I think disabling the self deployed DB by default would make sense.  An operator would need support the pgvecto-rs stuff as well.

**Comment by chriscowley** [comment]
Technically you can use the `backup` in the Bitnami chart that can be enabled:

```yaml
postgresql:
  enabled: true
   backup:
    enabled: true
    cronjob:
      storage:
        storageClass: "<something-external>"
```

However, it does not work straight away because Immich uses the postgresql user "immich" and the backup cronjob uses the user "postgres" which does not have password access. There must be someway of either

- passing the "immich" credentials through to the cronJob
- Giving "postgres" the necessary permissions (at DB initialisation?)

There is a "customUser" variable in the cronJob template of Bitnami's chart, but I just created a cronJob manually that used the correct credentials and went to put up some shelves instead.

**Comment by bo0tzz** [comment]
I wasn't aware the bitnami chart includes that, neat. With that I'll close this request.
